#测试URL
sys:
  km_sit_url: http://km-test.gtmsh.com/WX_Food_Tanyu/
  km_prod_url: http://wxapi.gtmsh.com/
  oa_sit_url: https://bk-test.gtmsh.com/admin/welcome
  api_sit_url: https://api-test.gtmsh.com

#日志配置
log:
  log_path: Log
  log_level: logging.DEBUG
  log_format: '%(asctime)s - %(name)s - %(filename)s - [line:%(lineno)d] - %(levelname)s -> %(message)s'

#tapd账号&密令
tapd:
  user: Ayz%+NkJ
  pwd: 43E6F048-CA6B-84BE-7A57-5C8C9BF461C5

#邮件配置
smtp:
  host: smtp.qq.com
  port: 465
  user: mikuya_9@qq.com
  pwd: dnlofayaldvveahg


#收发件人
email:
  sender: mikuya_9@qq.com
  receivers: zhongyun@gtmsh.com,xiangpengfei@gtmsh.com #多个收件人一定要用，分割，别看官方文档用list

#谷歌浏览器optioner配置

